/*
 * Created by JFormDesigner on Thu Jan 30 12:02:33 CET 2014
 */

package gameshop.advance.ui.swing.employee;

import com.jgoodies.forms.factories.CC;
import com.jgoodies.forms.layout.FormLayout;
import gameshop.advance.exceptions.ConfigurationException;
import gameshop.advance.exceptions.InvalidMoneyException;
import gameshop.advance.ui.swing.UIWindowSingleton;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.RemoteException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * @author Andrea
 */
public class PaymentPanel extends JPanel {
    
    public PaymentPanel() {
        initComponents();
        try {
            this.displayTotal.setText(SaleController.getInstance().getTotal().toString());
        } catch (NullPointerException ex) {
            UIWindowSingleton.getInstance().displayError("Ci sono problemi di comunicazione,"
                    + " si prega di controllare la configurazione del sistema.");
        } catch (RemoteException ex) {
            UIWindowSingleton.getInstance().displayError("Non è possibile contattare il server. "
                    + "Si prega di riprovare. Se il problema persiste, contattare l'amministratore di sistema.");
        } catch (ConfigurationException ex) {
            UIWindowSingleton.getInstance().displayError("Ci sono problemi nella lettura del file di configurazione: "+ex.getConfigurationPath()+"."
                    + " Per maggiori informazioni rivolgersi all'amministratore di sistema.");
        }
    }

    private void payButtonActionPerformed(ActionEvent e) {
        try{
            SaleController.getInstance().effettuaPagamento(Double.parseDouble(this.payment.getText()));
        } catch (NullPointerException ex) {
            UIWindowSingleton.getInstance().displayError("Ci sono problemi di comunicazione,"
                    + " si prega di controllare la configurazione del sistema.");
        } catch (RemoteException ex) {
            UIWindowSingleton.getInstance().displayError("Non è possibile contattare il server. "
                    + "Si prega di riprovare. Se il problema persiste, contattare l'amministratore di sistema.");
        } catch (ConfigurationException ex) {
            UIWindowSingleton.getInstance().displayError("Ci sono problemi nella lettura del file di configurazione: "+ex.getConfigurationPath()+"."
                    + " Per maggiori informazioni rivolgersi all'amministratore di sistema.");
        } catch (InvalidMoneyException ex) {
            UIWindowSingleton.getInstance().displayError("La quantità di denaro: "+ ex.getAmount().toString() +" non è sufficiente.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {
        // JFormDesigner - Component initialization - DO NOT MODIFY  //GEN-BEGIN:initComponents
        label1 = new JLabel();
        displayTotal = new JTextField();
        payment = new JTextField();
        label2 = new JLabel();
        payButton = new JButton();

        //======== this ========
        setLayout(new FormLayout(
            "$lcgap, 73dlu, $lcgap, 113dlu, 70dlu, $lcgap, 1dlu",
            "39dlu, $lgap, 30dlu, $lgap, 15dlu, $rgap, 31dlu, $pgap, 25dlu, 29dlu, $pgap"));

        //---- label1 ----
        label1.setText("Totale");
        label1.setFont(label1.getFont().deriveFont(label1.getFont().getSize() + 10f));
        label1.setAlignmentX(0.5F);
        add(label1, CC.xy(2, 3));

        //---- displayTotal ----
        displayTotal.setEditable(false);
        add(displayTotal, CC.xywh(4, 2, 2, 2));
        add(payment, CC.xywh(4, 6, 2, 2));

        //---- label2 ----
        label2.setText("Pagamento");
        label2.setFont(label2.getFont().deriveFont(label2.getFont().getSize() + 10f));
        label2.setAlignmentX(0.5F);
        add(label2, CC.xy(2, 7));

        //---- payButton ----
        payButton.setText("Paga");
        payButton.setFont(payButton.getFont().deriveFont(payButton.getFont().getSize() + 15f));
        payButton.setAlignmentX(0.5F);
        payButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                payButtonActionPerformed(e);
            }
        });
        add(payButton, CC.xywh(4, 9, 2, 2));
        // JFormDesigner - End of component initialization  //GEN-END:initComponents
    }

    // JFormDesigner - Variables declaration - DO NOT MODIFY  //GEN-BEGIN:variables
    private JLabel label1;
    private JTextField displayTotal;
    private JTextField payment;
    private JLabel label2;
    private JButton payButton;
    // JFormDesigner - End of variables declaration  //GEN-END:variables
}
